package animal.vhdl.logic;
/** <br>
 * 
 *
 * @author Lu,Zheng
 * @version 1.0
 */
public class LogicOr extends LogicGate{

	private static Character[][] and_table=
	{{LOGIC_UNINITIALIZED,LOGIC_UNINITIALIZED,LOGIC_UNINITIALIZED,LOGIC_STRONG_HIGH,LOGIC_UNINITIALIZED,LOGIC_UNINITIALIZED,LOGIC_UNINITIALIZED,LOGIC_STRONG_HIGH,LOGIC_UNINITIALIZED},
	 {LOGIC_UNINITIALIZED,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_HIGH,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_HIGH,LOGIC_STRONG_UNKNOWN},
	 {LOGIC_UNINITIALIZED,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_LOW,LOGIC_STRONG_HIGH,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_LOW,LOGIC_STRONG_HIGH,LOGIC_STRONG_UNKNOWN},
	 {LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH},
	 {LOGIC_UNINITIALIZED,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_HIGH,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_HIGH,LOGIC_STRONG_UNKNOWN},
	 {LOGIC_UNINITIALIZED,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_HIGH,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_HIGH,LOGIC_STRONG_UNKNOWN},
	 {LOGIC_STRONG_LOW,LOGIC_STRONG_LOW,LOGIC_STRONG_LOW,LOGIC_STRONG_LOW,LOGIC_STRONG_LOW,LOGIC_STRONG_LOW,LOGIC_STRONG_LOW,LOGIC_STRONG_LOW,LOGIC_STRONG_LOW},
	 {LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH,LOGIC_STRONG_HIGH},
	 {LOGIC_UNINITIALIZED,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_HIGH,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_UNKNOWN,LOGIC_STRONG_HIGH,LOGIC_STRONG_UNKNOWN}};
	public LogicOr(char [] inputList){
		logicResult='0';
		int coordinateOr[]=new int [2];
		if (inputList.length<2){
			Exception nis=new Exception("Or-Gate have less than two Input");
			try {
				throw nis;
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}		
		else{
			for(int i=0;i<inputList.length;i++){
				coordinateOr=findResult(logicResult,inputList[i]);
				logicResult=and_table[coordinateOr[0]][coordinateOr[1]];
		}
		}

}

}
