package animalscript.extensions;

// insert any Java system classes you need here
import java.io.IOException;
import java.util.Hashtable;

import animal.misc.ParseSupport;
import animalscript.core.AnimalParseSupport;
import animalscript.core.AnimalScriptInterface;
import animalscript.core.BasicParser;

/**
 * This class provides an import filter for AnimalScript XXX commands
 * 
 * @author <a href="mailto:roessling@acm.org">Guido R&ouml;&szlig;ling</a>
 * @version 1.0 2000-06-17
 */
public class EmbeddedFileSupport extends BasicParser implements
		AnimalScriptInterface {
	// ========================= attributes =========================

	/**
	 * instantiates the key class dispatcher mapping keyword to definition type
	 */
	public EmbeddedFileSupport() {
		// Use the following commands in here to instantiate the method
		// callup mechanism:
		// 1. instantiate the local XProperties object
		handledKeywords = new Hashtable<String, Object>();

		// 2. For all handled keywords, associate("put") keyword with method name
		// NOTE: you *must* use lowercase for the whole keyword!!!
		handledKeywords.put("embed", "parseEmbeddedFile");
	}

	// ===================================================================
	// interface methods
	// ===================================================================

	/**
	 * Determine depending on the command passed if a new step is needed Also keep
	 * in mind that we might be in a grouped step using the {...} form. Usually,
	 * every command not inside such a grouped step is contained in a new step.
	 * However, this is not the case for operations without visible effect -
	 * mostly maintenance or declaration entries.
	 * 
	 * @param command
	 *          the command used for the decision.
	 * @return true if a new step must be generated
	 */
	public boolean generateNewStep(String command) {
		// adapt the following basic definition to your needs...
		return false;
	}

	// ===================================================================
	// Animator parsing routines
	// ===================================================================

	/**
	 * Create a array from the description read from the StreamTokenizer. The
	 * description is usually generated by other programs and dumped in a file or
	 * on System.out.
	 */
	public void parseEmbeddedFile() throws IOException {
		ParseSupport.parseWord(stok, "embed command");
		String filename = AnimalParseSupport.parseText(stok, "filename to embed");
		generateStreamTokenizer(filename, true);
	}
} // class EmbeddedFileSupport
