/* Generated By:JJTree: Do not edit this line. Div.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY= */
package algoanim.executors.formulaparser;

public class Div extends SimpleNode {
  public Div(int id) {
    super(id);
  }

  public Div(FormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d95aee7499d6aed78bc24281eb277697 (do not edit this line) */
