/* Generated By:JavaCC: Do not edit this line. FormulaParserTreeConstants.java Version 4.1 */
package algoanim.executors.formulaparser;

public interface FormulaParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTPLUS = 2;
  public int JJTMINUS = 3;
  public int JJTMULT = 4;
  public int JJTDIV = 5;
  public int JJTNUMBER = 6;
  public int JJTIDENTIFIER = 7;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Plus",
    "Minus",
    "Mult",
    "Div",
    "Number",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=0c2278e21117258b73862decafe9192f (do not edit this line) */
