/* Generated By:JJTree: Do not edit this line. Identifier.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY= */
package algoanim.executors.formulaparser;

public class Identifier extends SimpleNode {
  public Identifier(int id) {
    super(id);
  }

  public Identifier(FormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f64f04499d959cc3eefaac9a1b28cf9b (do not edit this line) */
