/* Generated By:JJTree: Do not edit this line. Minus.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY= */
package algoanim.executors.formulaparser;

public class Minus extends SimpleNode {
  public Minus(int id) {
    super(id);
  }

  public Minus(FormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=99dd534d51e71d07c04db5718d63bbc1 (do not edit this line) */
