/* Generated By:JJTree: Do not edit this line. Mult.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY= */
package algoanim.executors.formulaparser;

public class Mult extends SimpleNode {
  public Mult(int id) {
    super(id);
  }

  public Mult(FormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=534590e63cf61fe4c9fcd97913526ddc (do not edit this line) */
