/* Generated By:JJTree: Do not edit this line. Number.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY= */
package algoanim.executors.formulaparser;

public class Number extends SimpleNode {
  public Number(int id) {
    super(id);
  }

  public Number(FormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a5bdafb60963bf15f72cfa4dc8d9495d (do not edit this line) */
