/* Generated By:JJTree: Do not edit this line. Plus.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY= */
package algoanim.executors.formulaparser;

public class Plus extends SimpleNode {
  public Plus(int id) {
    super(id);
  }

  public Plus(FormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eb4429b70657dfa2484796577ff8bab9 (do not edit this line) */
