/* Generated By:JJTree: Do not edit this line. Root.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY= */
package algoanim.executors.formulaparser;

public class Root extends SimpleNode {
  public Root(int id) {
    super(id);
  }

  public Root(FormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e6d8b30a3d292fa6fa8e5c477277c5b0 (do not edit this line) */
