/*
 * Created on 14.07.2004
 *
 * To change the template for this generated file go to
 * Window - Preferences - Java - Code Generation - Code and Comments
 */
package animal.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import animal.exchange.AnimationExporter;
import animal.exchange.AnimationImporter;
import animal.exchange.AnimationPrintJob;
import animal.main.Animal;
import animal.main.Animation;
import animal.misc.MessageDisplay;

/**
 * @author guido
 *
 * To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Generation - Code and Comments
 */
public class MainMenuBarController2 implements ActionListener {

  /**
   * The animal instance of which we will be working!
   */
  private Animal animal;
  
  /**
   * The instance for handling direct AnimalScript input
   */
  private AnimalScriptInputWindow scriptInputWindow;
  
  
  /**
   * creates a new main menu controller
   * 
   * @param animalInstance the current instance of Animal
   */
  public MainMenuBarController2(Animal animalInstance) {
    super();
    
    // store the reference to the Animal instance!
    animal = animalInstance;
  }

  
  /**
   * handle events generated by the main menu tool bar
   * 
   * @param event the ActionEvent generated by some type of user interaction
   */
  public void actionPerformed(ActionEvent event) {
    // make sure the Animal reference exists!
    if (animal == null)
      animal = Animal.get();
    
    String command = event.getActionCommand();
    if (command.equals(MainToolBar.INPUT)) {
      if (scriptInputWindow == null)
        scriptInputWindow = new AnimalScriptInputWindow(animal);
      scriptInputWindow.initScriptingGUI();
    }
    else if (command.equals(MainToolBar.NEW))
      animal.newFile();
    else if (command.equals(MainToolBar.OPEN))
      AnimationImporter.importAnimation();
    else if (command.equals(MainToolBar.PRINT))
      new AnimationPrintJob(animal);
    else if (command.equals(MainToolBar.RELOAD))
      animal.reloadFile();
    else if (command.equals(MainToolBar.REPOSITORY))
      animal.openRepository();
    else if (command.equals(MainToolBar.SAVE)) {
      Animation currentAnimation = animal.getAnimation();
      if (currentAnimation != null)
        AnimationExporter.saveAnimation(currentAnimation);
    }
    else if (command.equals(MainToolBar.SAVE_AS)) {
      Animation currentAnimation = animal.getAnimation();
      if (currentAnimation != null)
        AnimationExporter.exportAnimation(currentAnimation);
    }
    else if (MainToolBar.CLEAR.equals(command)) {
      AnimalMainWindow.getOutputArea().setText(null);
    }
    else 
      MessageDisplay.errorMsg("nothingAssoc", command, 
          MessageDisplay.RUN_ERROR);
  }
}
