package generators.graph.pagerank;

public enum SourceCodePosition {
	NODE_WEIGHT_CREATION,
	
	EDGE_WEIGHT_CREATION,
	RANDOM_SURFER_EDGE_WEIGHT_CREATION,
	RANDOM_SURFER_PARAMETER_CREATION,
	
	BEGIN_NEW_ITERATION,
	UPDATE_OLD_NODE_WEIGHTS,
	EVALUATE_TERMINATION_CONSTRAINT,
	CALCULATE_NODE_WEIGHT;
}
